"""Generate derived, read-only requirement views from the canonical SRS.

Single source of truth: ``docs/cpm_fm_requirements.md`` (hand-edited, ISO 29148
conformant). This script never modifies it — it only emits slim, derived views
that small-context LLMs (and humans) can load instead of the whole 40K-token
SRS:

  * ``docs/requirements_views/requirements_index.md``
        Terse, section-grouped one-line-per-requirement summary, for *broad*
        understanding.
  * ``docs/requirements_views/code_to_requirements.md``
        Source file -> requirement IDs it implements (from ``Satisfies:``
        docstring tags), for *targeted* work — find the file you're editing,
        then read just those IDs.
  * ``docs/requirements_views/code_to_requirements.json``
        The same map, machine-readable, for tooling (drift checks, PR-impact
        lookups, etc.).

Usage (run from anywhere; paths are resolved relative to this file):

    python tools/traceability_sync/generate_views.py
    python tools/traceability_sync/generate_views.py --check

``--check`` regenerates the views in memory and exits non-zero if the committed
files are stale or missing, writing nothing. It is the hook for a pre-commit /
CI freshness check (Stage 3); the plain invocation rewrites the files.

The output is deterministic (no timestamps, sorted keys) so ``--check`` diffs
are stable.
"""

import argparse
import json
import re
import sys
from pathlib import Path

# Allow sibling imports (parser_docs / parser_code) regardless of CWD or how
# the script is launched — mirrors the convention used by agent_toolset.py.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from parser_code import scan_codebase  # noqa: E402
from parser_docs import _split_row  # noqa: E402

# ---------------------------------------------------------------------------
# Paths (resolved from this file, so CWD does not matter)
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[2]
CODE_ROOT = REPO_ROOT / "src"
REQ_FILE = REPO_ROOT / "docs" / "cpm_fm_requirements.md"
OUT_DIR = REPO_ROOT / "docs" / "requirements_views"
INDEX_MD = OUT_DIR / "requirements_index.md"
CODE_MAP_MD = OUT_DIR / "code_to_requirements.md"
CODE_MAP_JSON = OUT_DIR / "code_to_requirements.json"

# A requirement-table row is one whose first cell is a bare requirement ID.
# This naturally excludes the §9 traceability rows (first cell is a source
# section) and the §10 issue log (first cell is an OI-xx id).
_ID_RE = re.compile(r"^(?:STR|FR|UIR|IFR|DR|CR|NFR)-\d+[a-z]?$")
_ID_PARTS_RE = re.compile(r"^([A-Z]+)-(\d+)([a-z]?)$")

# Abbreviations whose trailing period must not be mistaken for a sentence end
# when truncating a summary.
_ABBREV = {"e.g.", "i.e.", "etc.", "vs.", "cf.", "incl.", "approx."}

_GENERATED_BANNER = (
    "<!-- GENERATED by tools/traceability_sync/generate_views.py — DO NOT EDIT.\n"
    "     Regenerate after editing docs/cpm_fm_requirements.md or code "
    "`Satisfies:` tags. -->"
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _id_sort_key(req_id: str) -> tuple:
    """Natural sort key for a requirement ID: (prefix, number, suffix)."""
    m = _ID_PARTS_RE.match(req_id)
    if not m:
        return (req_id, 0, "")
    return (m.group(1), int(m.group(2)), m.group(3))


def summarize(description: str, max_words: int = 15) -> str:
    """Derive a terse summary from a requirement's full text.

    Prefers the first sentence; caps at ``max_words`` words. Faithful to the
    source wording (no rephrasing) so the index never drifts in meaning from
    the canonical SRS — it only shortens.
    """
    text = re.sub(r"\s+", " ", description.replace("`", "")).strip()
    words = text.split(" ")

    cut_at = None
    for i in range(min(len(words), max_words)):
        w = words[i]
        if w.endswith((".", ":", ";")) and w.lower() not in _ABBREV:
            cut_at = i + 1
            break
    if cut_at is None:
        cut_at = min(len(words), max_words)

    truncated = cut_at < len(words)
    summary = " ".join(words[:cut_at]).rstrip(" .:;,")
    return summary + ("…" if truncated else "")


def code_impl(source_cell: str) -> str:
    """Extract just the code citation from a Source cell.

    A Source cell may carry a legacy doc reference, an ``impl. `file:func``
    citation, or both (e.g. ``App_Design §Purpose; impl. `app.py:main```). The
    index shows only the code part; rows with no code citation show ``—``.
    """
    if not source_cell or source_cell in ("Unmapped", "—", "None"):
        return "—"
    idx = source_cell.lower().find("impl.")
    if idx == -1:
        return "—"
    cite = source_cell[idx + len("impl.") :].replace("`", "")
    cite = re.sub(r"\s+", " ", cite).strip()
    return cite or "—"


# ---------------------------------------------------------------------------
# Parsing the SRS into ordered sections of requirement rows
# ---------------------------------------------------------------------------
def parse_sections(req_file: Path) -> list:
    """Return ``[(section_title, [(id, description, source), ...]), ...]`` in
    document order, including only sections that contain requirement rows.

    Reuses :func:`parser_docs._split_row` for robust, escaped-pipe-aware cell
    splitting.
    """
    lines = req_file.read_text(encoding="utf-8").splitlines()

    sections: list = []
    current_title = None
    current_rows = None  # lazily created when the section's first row appears

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#"):
            current_title = stripped.lstrip("#").strip()
            current_rows = None
            continue
        if stripped.startswith("|"):
            cells = _split_row(stripped)
            if len(cells) >= 2 and _ID_RE.match(cells[0]):
                if current_rows is None:
                    current_rows = []
                    sections.append((current_title or "Ungrouped", current_rows))
                current_rows.append((cells[0], cells[1], cells[-1]))

    return sections


# ---------------------------------------------------------------------------
# View builders (pure: text in -> text out, for --check determinism)
# ---------------------------------------------------------------------------
def build_index_md(sections: list) -> str:
    out = [
        "# Requirements Index (GENERATED)",
        "",
        _GENERATED_BANNER,
        "",
        "Terse, section-grouped summary of `docs/cpm_fm_requirements.md` (the "
        "canonical SRS).",
        "Each row gives a requirement ID, a ~15-word summary, and its code "
        "implementation.",
        "Read this for **broad understanding**; open the full SRS only when you "
        "need exact wording, priority, or verification method.",
        "",
    ]
    total = 0
    for title, rows in sections:
        out.append(f"## {title}")
        out.append("")
        out.append("| ID | Summary | Impl |")
        out.append("|----|---------|------|")
        for req_id, desc, source in rows:
            out.append(f"| {req_id} | {summarize(desc)} | {code_impl(source)} |")
            total += 1
        out.append("")
    out.insert(7, f"_{total} requirements across {len(sections)} sections._")
    out.insert(8, "")
    return "\n".join(out).rstrip() + "\n"


def build_code_map(code_root: Path, defined_ids: set) -> dict:
    """Build ``{source_file: [req_id, ...]}`` from code ``Satisfies:`` tags.

    Paths are repo-relative with forward slashes; IDs are de-duplicated and
    naturally sorted.

    ``Satisfies:`` ranges (e.g. ``DR-001-DR-032``) are expanded across the
    numeric span by :func:`parser_code.scan_codebase`, which can cover gaps in
    the deliberately non-contiguous numbering (§6 leaves DR-007–009 etc.
    undefined). Such range-derived IDs that match no defined requirement are
    dropped — mirroring the traceability tool — so the map references only real
    requirements. An *explicit* tag citing an undefined ID is kept, because that
    is a genuine authoring error worth surfacing rather than hiding.
    """
    elements = scan_codebase(str(code_root))
    by_file: dict = {}
    for elem in elements:
        if elem.from_range and elem.requirement_id not in defined_ids:
            continue
        rel = elem.module.replace("\\", "/")
        full = f"src/{rel}"
        by_file.setdefault(full, set()).add(elem.requirement_id)
    return {
        path: sorted(by_file[path], key=_id_sort_key)
        for path in sorted(by_file)
    }


def build_code_map_md(code_map: dict) -> str:
    out = [
        "# Code → Requirements Map (GENERATED)",
        "",
        _GENERATED_BANNER,
        "",
        "Maps each source file to the requirement IDs it implements, derived "
        "from `Satisfies:` docstring tags in the code.",
        "Use this for **targeted work**: find the file you're editing, then read "
        "just those IDs in `requirements_index.md` or the full SRS — instead of "
        "loading the whole specification.",
        "",
        f"_{len(code_map)} source files; "
        f"{sum(len(v) for v in code_map.values())} file→requirement links._",
        "",
        "| Source file | Requirement IDs |",
        "|-------------|-----------------|",
    ]
    for path, ids in code_map.items():
        out.append(f"| {path} | {', '.join(ids)} |")
    return "\n".join(out).rstrip() + "\n"


def build_code_map_json(code_map: dict) -> str:
    return json.dumps(code_map, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def generate() -> dict:
    """Build all view contents in memory. Returns ``{path: content}``."""
    sections = parse_sections(REQ_FILE)
    defined_ids = {row[0] for _, rows in sections for row in rows}
    code_map = build_code_map(CODE_ROOT, defined_ids)
    return {
        INDEX_MD: build_index_md(sections),
        CODE_MAP_MD: build_code_map_md(code_map),
        CODE_MAP_JSON: build_code_map_json(code_map),
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if committed views are stale/missing; write nothing.",
    )
    args = parser.parse_args(argv)

    if not REQ_FILE.exists():
        print(f"ERROR: requirements file not found: {REQ_FILE}", file=sys.stderr)
        return 2

    contents = generate()

    if args.check:
        stale = []
        for path, content in contents.items():
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                stale.append(path)
        if stale:
            print("Requirement views are STALE — run generate_views.py:")
            for path in stale:
                print(f"  - {path.relative_to(REPO_ROOT)}")
            return 1
        print("Requirement views are up to date.")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in contents.items():
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
