"""Generate derived, read-only requirement views from the canonical SRS.

Single source of truth: ``docs/cpm_fm_requirements.md`` (hand-edited, ISO 29148
conformant). This script never modifies it — it only emits slim, derived views
that small-context LLMs (and humans) can load instead of the whole 40K-token
SRS:

  * ``docs/requirements_views/requirements_index.md``
        Terse, section-grouped one-line-per-requirement summary, for *broad*
        understanding.
  * ``docs/requirements_views/code_to_requirements.md``
        Source file -> requirement IDs it implements (from ``Satisfies:``
        docstring tags), for *targeted* work — find the file you're editing,
        then read just those IDs.
  * ``docs/requirements_views/code_to_requirements.json``
        The same map, machine-readable, for tooling (drift checks, PR-impact
        lookups, etc.).

Usage (run from anywhere; paths are resolved relative to this file):

    python tools/traceability_sync/generate_views.py
    python tools/traceability_sync/generate_views.py --check

``--check`` regenerates the views in memory and exits non-zero if the committed
files are stale or missing, writing nothing. It is the hook for a pre-commit /
CI freshness check (Stage 3); the plain invocation rewrites the files.

The output is deterministic (no timestamps, sorted keys) so ``--check`` diffs
are stable.
"""

import argparse
import json
import re
import sys
from pathlib import Path

# Allow sibling imports (parser_docs / parser_code) regardless of CWD or how
# the script is launched — mirrors the convention used by agent_toolset.py.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from parser_code import scan_codebase  # noqa: E402
from parser_docs import _split_row  # noqa: E402

# ---------------------------------------------------------------------------
# Paths (resolved from this file, so CWD does not matter)
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[2]
CODE_ROOT = REPO_ROOT / "src"
TESTS_ROOT = REPO_ROOT / "tests"
REQ_FILE = REPO_ROOT / "docs" / "cpm_fm_requirements.md"
ARCH_FILE = REPO_ROOT / "docs" / "cpm_fm_architecture.md"
# Requirement rows live in the SRS plus its architecture companion (the CR-/NFR-
# architectural constraints were extracted there). Both are parsed, in this
# order, so the index and the defined-ID set cover every requirement.
SPEC_FILES = [REQ_FILE, ARCH_FILE]
OUT_DIR = REPO_ROOT / "docs" / "requirements_views"
INDEX_MD = OUT_DIR / "requirements_index.md"
CODE_MAP_MD = OUT_DIR / "code_to_requirements.md"
CODE_MAP_JSON = OUT_DIR / "code_to_requirements.json"
REQ_TESTS_MD = OUT_DIR / "requirements_to_tests.md"
REQ_TESTS_JSON = OUT_DIR / "requirements_to_tests.json"

# A requirement-table row is one whose first cell is a bare requirement ID.
# This naturally excludes the §9 traceability rows (first cell is a source
# section) and the §10 issue log (first cell is an OI-xx id).
_ID_RE = re.compile(r"^(?:STR|FR|UIR|IFR|DR|CR|NFR)-\d+[a-z]?$")
_ID_PARTS_RE = re.compile(r"^([A-Z]+)-(\d+)([a-z]?)$")

# Abbreviations whose trailing period must not be mistaken for a sentence end
# when truncating a summary.
_ABBREV = {"e.g.", "i.e.", "etc.", "vs.", "cf.", "incl.", "approx."}

_GENERATED_BANNER = (
    "<!-- GENERATED by tools/traceability_sync/generate_views.py — DO NOT EDIT.\n"
    "     Regenerate after editing the specs, code `Satisfies:` tags, or test "
    "`Verifies:` tags. -->"
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _id_sort_key(req_id: str) -> tuple:
    """Natural sort key for a requirement ID: (prefix, number, suffix)."""
    m = _ID_PARTS_RE.match(req_id)
    if not m:
        return (req_id, 0, "")
    return (m.group(1), int(m.group(2)), m.group(3))


def summarize(description: str, max_words: int = 15) -> str:
    """Derive a terse summary from a requirement's full text.

    Prefers the first sentence; caps at ``max_words`` words. Faithful to the
    source wording (no rephrasing) so the index never drifts in meaning from
    the canonical SRS — it only shortens.
    """
    text = re.sub(r"\s+", " ", description.replace("`", "")).strip()
    words = text.split(" ")

    cut_at = None
    for i in range(min(len(words), max_words)):
        w = words[i]
        if w.endswith((".", ":", ";")) and w.lower() not in _ABBREV:
            cut_at = i + 1
            break
    if cut_at is None:
        cut_at = min(len(words), max_words)

    truncated = cut_at < len(words)
    summary = " ".join(words[:cut_at]).rstrip(" .:;,")
    return summary + ("…" if truncated else "")


def code_impl(source_cell: str) -> str:
    """Extract just the code citation from a Source cell.

    A Source cell may carry a legacy doc reference, an ``impl. `file:func``
    citation, or both (e.g. ``App_Design §Purpose; impl. `app.py:main```). The
    index shows only the code part; rows with no code citation show ``—``.
    """
    if not source_cell or source_cell in ("Unmapped", "—", "None"):
        return "—"
    idx = source_cell.lower().find("impl.")
    if idx == -1:
        return "—"
    cite = source_cell[idx + len("impl.") :].replace("`", "")
    cite = re.sub(r"\s+", " ", cite).strip()
    return cite or "—"


# ---------------------------------------------------------------------------
# Structural table validation
# ---------------------------------------------------------------------------
def validate_tables(spec_file: Path) -> list[str]:
    """Check every Markdown table in ``spec_file`` for column-count integrity.

    For each table (a header row immediately followed by a ``|---|`` separator),
    every data row must split — on *unescaped* pipes, via :func:`_split_row`,
    so an escaped ``\\|`` inside a cell is left intact — to exactly the header's
    cell count. A literal, unescaped ``|`` inside a cell (the DR-046 bug)
    fragments the row past the header count and is reported here.

    Returns a list of human-readable error strings (``file:line: ...``); an
    empty list means every table is well-formed. Reporting rather than raising
    lets the caller aggregate errors across files before exiting.
    """
    lines = spec_file.read_text(encoding="utf-8").splitlines()
    errors: list[str] = []
    n = len(lines)
    i = 0
    while i < n:
        header = lines[i].strip()
        nxt = lines[i + 1].strip() if i + 1 < n else ""
        # A table header is a pipe row whose next line is a |---| separator.
        if header.startswith("|") and nxt.startswith("|") and "---" in nxt:
            header_count = len(_split_row(header))
            j = i + 2
            while j < n and lines[j].strip().startswith("|"):
                row = lines[j].strip()
                # A second separator row (rare) is layout, not data — skip it.
                if "---" not in row:
                    count = len(_split_row(row))
                    if count != header_count:
                        errors.append(
                            f"{spec_file.name}:{j + 1}: expected {header_count} "
                            f"cells but row has {count} (unescaped '|' in a cell?) "
                            f"— {row}"
                        )
                j += 1
            i = j  # resume past the table block
        else:
            i += 1
    return errors


# ---------------------------------------------------------------------------
# Parsing the SRS into ordered sections of requirement rows
# ---------------------------------------------------------------------------
def parse_sections(req_file: Path) -> list:
    """Return ``[(section_title, [(id, description, source), ...]), ...]`` in
    document order, including only sections that contain requirement rows.

    Reuses :func:`parser_docs._split_row` for robust, escaped-pipe-aware cell
    splitting.
    """
    lines = req_file.read_text(encoding="utf-8").splitlines()

    sections: list = []
    current_title = None
    current_rows = None  # lazily created when the section's first row appears

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#"):
            current_title = stripped.lstrip("#").strip()
            current_rows = None
            continue
        if stripped.startswith("|"):
            cells = _split_row(stripped)
            if len(cells) >= 2 and _ID_RE.match(cells[0]):
                if current_rows is None:
                    current_rows = []
                    sections.append((current_title or "Ungrouped", current_rows))
                current_rows.append((cells[0], cells[1], cells[-1]))

    return sections


# ---------------------------------------------------------------------------
# View builders (pure: text in -> text out, for --check determinism)
# ---------------------------------------------------------------------------
def build_index_md(sections: list) -> str:
    out = [
        "# Requirements Index (GENERATED)",
        "",
        _GENERATED_BANNER,
        "",
        "Terse, section-grouped summary of `docs/cpm_fm_requirements.md` (the "
        "canonical SRS) and its architecture companion "
        "`docs/cpm_fm_architecture.md` (the CR-/NFR- constraints).",
        "Each row gives a requirement ID, a ~15-word summary, and its code "
        "implementation.",
        "Read this for **broad understanding**; open the full SRS only when you "
        "need exact wording, priority, or verification method.",
        "",
    ]
    total = 0
    for title, rows in sections:
        out.append(f"## {title}")
        out.append("")
        out.append("| ID | Summary | Impl |")
        out.append("|----|---------|------|")
        for req_id, desc, source in rows:
            out.append(f"| {req_id} | {summarize(desc)} | {code_impl(source)} |")
            total += 1
        out.append("")
    out.insert(7, f"_{total} requirements across {len(sections)} sections._")
    out.insert(8, "")
    return "\n".join(out).rstrip() + "\n"


def build_code_map(code_root: Path, defined_ids: set) -> dict:
    """Build ``{source_file: [req_id, ...]}`` from code ``Satisfies:`` tags.

    Paths are repo-relative with forward slashes; IDs are de-duplicated and
    naturally sorted.

    ``Satisfies:`` ranges (e.g. ``DR-001-DR-032``) are expanded across the
    numeric span by :func:`parser_code.scan_codebase`, which can cover gaps in
    the deliberately non-contiguous numbering (§6 leaves DR-007–009 etc.
    undefined). Such range-derived IDs that match no defined requirement are
    dropped — mirroring the traceability tool — so the map references only real
    requirements. An *explicit* tag citing an undefined ID is kept, because that
    is a genuine authoring error worth surfacing rather than hiding.
    """
    elements = scan_codebase(str(code_root))
    by_file: dict = {}
    for elem in elements:
        if elem.from_range and elem.requirement_id not in defined_ids:
            continue
        rel = elem.module.replace("\\", "/")
        full = f"src/{rel}"
        by_file.setdefault(full, set()).add(elem.requirement_id)
    return {
        path: sorted(by_file[path], key=_id_sort_key)
        for path in sorted(by_file)
    }


def build_code_map_md(code_map: dict) -> str:
    out = [
        "# Code → Requirements Map (GENERATED)",
        "",
        _GENERATED_BANNER,
        "",
        "Maps each source file to the requirement IDs it implements, derived "
        "from `Satisfies:` docstring tags in the code.",
        "Use this for **targeted work**: find the file you're editing, then read "
        "just those IDs in `requirements_index.md` or the full SRS — instead of "
        "loading the whole specification.",
        "",
        f"_{len(code_map)} source files; "
        f"{sum(len(v) for v in code_map.values())} file→requirement links._",
        "",
        "| Source file | Requirement IDs |",
        "|-------------|-----------------|",
    ]
    for path, ids in code_map.items():
        out.append(f"| {path} | {', '.join(ids)} |")
    return "\n".join(out).rstrip() + "\n"


def build_code_map_json(code_map: dict) -> str:
    return json.dumps(code_map, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# Requirement -> test coverage (from test `Verifies:` tags)
# ---------------------------------------------------------------------------
def build_req_to_tests(tests_root: Path, defined_ids: set) -> dict:
    """Map each defined requirement to the test(s) that verify it.

    The mirror of :func:`build_code_map` for the test suite: it scans
    ``tests_root`` for ``Verifies:`` docstring tags (instead of code
    ``Satisfies:`` tags) and classifies the result against ``defined_ids`` —
    the set of requirement IDs the SRS and architecture companion actually
    define.

    A range-derived ID (e.g. from ``Verifies: DR-001-DR-032``) that matches no
    defined requirement is dropped — such a span can cover gaps in the
    deliberately non-contiguous numbering, mirroring :func:`build_code_map`. An
    *explicit* ``Verifies:`` tag citing an undefined ID is surfaced as ``stale``,
    because that is a genuine authoring error worth flagging.

    Returns ``{"covered": {req_id: [loc, ...]}, "untested": [req_id, ...],
    "stale": {req_id: [loc, ...]}}`` where each ``loc`` is
    ``"<tests-dir>/<file>:<test>"``. Keys and lists are naturally sorted so the
    output is deterministic for the ``--check`` drift gate.
    """
    prefix = tests_root.name
    elements = scan_codebase(str(tests_root), tag="Verifies:")
    covered: dict[str, set] = {}
    stale: dict[str, set] = {}
    for elem in elements:
        rel = elem.module.replace("\\", "/")
        loc = f"{prefix}/{rel}:{elem.name}"
        if elem.requirement_id in defined_ids:
            covered.setdefault(elem.requirement_id, set()).add(loc)
        elif elem.from_range:
            continue  # range-shorthand gap-filler, not a real requirement
        else:
            stale.setdefault(elem.requirement_id, set()).add(loc)
    untested = sorted(defined_ids - set(covered), key=_id_sort_key)
    return {
        "covered": {
            rid: sorted(covered[rid]) for rid in sorted(covered, key=_id_sort_key)
        },
        "untested": untested,
        "stale": {
            rid: sorted(stale[rid]) for rid in sorted(stale, key=_id_sort_key)
        },
    }


def build_req_to_tests_md(coverage: dict, total_defined: int) -> str:
    covered = coverage["covered"]
    untested = coverage["untested"]
    stale = coverage["stale"]
    out = [
        "# Requirements → Tests Map (GENERATED)",
        "",
        _GENERATED_BANNER,
        "",
        "Maps each requirement to the test(s) that verify it, derived from "
        "`Verifies:` docstring tags in the test suite.",
        "Use it to see which requirements have automated coverage, which do not, "
        "and which `Verifies:` tags cite an unknown requirement ID.",
        "",
        f"_{len(covered)}/{total_defined} requirements have a verifying test; "
        f"{len(untested)} untested; {len(stale)} stale tag(s)._",
        "",
        "## Covered requirements",
        "",
        "| Requirement ID | Verifying tests |",
        "|----------------|-----------------|",
    ]
    for rid, locs in covered.items():
        cites = ", ".join(f"`{loc}`" for loc in locs)
        out.append(f"| {rid} | {cites} |")
    out += ["", "## Untested requirements", ""]
    if untested:
        out.append("These defined requirements have no `Verifies:` test tag:")
        out.append("")
        out.extend(f"- {rid}" for rid in untested)
    else:
        out.append(
            "_None — every defined requirement has at least one verifying test._"
        )
    out += ["", "## Stale `Verifies:` tags", ""]
    if stale:
        out.append(
            "These `Verifies:` tags cite an ID not defined in the SRS or "
            "architecture companion (fix the tag or add the requirement):"
        )
        out.append("")
        for rid, locs in stale.items():
            cites = ", ".join(f"`{loc}`" for loc in locs)
            out.append(f"- {rid} — {cites}")
    else:
        out.append("_None — every `Verifies:` tag cites a defined requirement._")
    return "\n".join(out).rstrip() + "\n"


def build_req_to_tests_json(coverage: dict) -> str:
    return json.dumps(coverage, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def generate() -> dict:
    """Build all view contents in memory. Returns ``{path: content}``."""
    sections = []
    for spec_file in SPEC_FILES:
        sections.extend(parse_sections(spec_file))
    defined_ids = {row[0] for _, rows in sections for row in rows}
    code_map = build_code_map(CODE_ROOT, defined_ids)
    coverage = build_req_to_tests(TESTS_ROOT, defined_ids)
    return {
        INDEX_MD: build_index_md(sections),
        CODE_MAP_MD: build_code_map_md(code_map),
        CODE_MAP_JSON: build_code_map_json(code_map),
        REQ_TESTS_MD: build_req_to_tests_md(coverage, len(defined_ids)),
        REQ_TESTS_JSON: build_req_to_tests_json(coverage),
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if committed views are stale/missing; write nothing.",
    )
    args = parser.parse_args(argv)

    for spec_file in SPEC_FILES:
        if not spec_file.exists():
            print(f"ERROR: spec file not found: {spec_file}", file=sys.stderr)
            return 2

    # Structural guard (both --check and the write path): a malformed table row
    # would otherwise mis-parse silently and corrupt the generated views.
    table_errors: list[str] = []
    for spec_file in SPEC_FILES:
        table_errors.extend(validate_tables(spec_file))
    if table_errors:
        print("Malformed requirement-table row(s) — cell count != header:", file=sys.stderr)
        for err in table_errors:
            print(f"  - {err}", file=sys.stderr)
        return 3

    contents = generate()

    if args.check:
        stale = []
        for path, content in contents.items():
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                stale.append(path)
        if stale:
            print("Requirement views are STALE — run generate_views.py:")
            for path in stale:
                print(f"  - {path.relative_to(REPO_ROOT)}")
            return 1
        print("Requirement views are up to date.")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in contents.items():
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
